#
# Copyright 2024 Google LLC
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

site_name: JIT Groups
site_url: https://googlecloudplatform.github.io/jit-groups/
theme:
  name: material
  custom_dir: overrides
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - navigation.expand
  palette:
    primary: #006CBE
  icon:
    repo: fontawesome/brands/github
    admonition:
        info: fontawesome/solid/user-shield
extra:
  generator: false
  analytics:
    provider: google
    property: G-V2SJXHS47L
    
extra_css:
  - stylesheets/extra.css
  
repo_name: jit-groups
repo_url: https://github.com/GoogleCloudPlatform/jit-groups
copyright: |
    JIT Groups is an open-source project developed and maintained by the Google Cloud Solutions Architects team.<br>
    Copyright &copy; 2019-2025 Google LLC<br>
    <a href='https://cloud.google.com/'><img src='https://googlecloudplatform.github.io/jit-groups/images/cloud.svg' width='240' height='160'/></a>

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
nav:
  - 'JIT Groups':
      - Discover:
        - 'Overview': 'index.md'
        - 'Concepts': 'jitgroups-concepts.md'
      - 'Deploy':
        - 'Deploy JIT Groups': 'jitgroups-deploy.md'
        - 'Add an environment': 'jitgroups-environment.md'
        - 'Set up continuous deployment': 'jitgroups-continuous-deployment.md'
        - 'Upgrade from JIT Access': 'jitaccess-upgrade.md'
      - 'Extend':
          - 'Set up a development environment': development-environment.md
      - 'Reference':
          - 'Policy documents': policy-reference.md
          - 'Configuration options': 'jitgroups-options.md'
  - JIT Access:
    - Discover: 
      - 'Overview': 'jitaccess-overview.md'
      - 'Multi-party approval': multi-party-approval.md
      - 'Notifications': pubsub-notifications.md
    - 'Deploy JIT Access':
      - 'Deploy or upgrade JIT Access': jitaccess-deploy.md
      - 'Configure multi party approval': configure-multi-party-approval.md
      - 'Configure notifications': configure-pubsub-notifications.md
      - 'Configure catalogs': configure-catalogs.md
      - 'Access VPC service perimeters': configure-vpcsc.md
      - 'Use health checks': health-checks.md
    - 'Use JIT Access':
      - 'Resource conditions': resource-conditions.md
    - 'Customize JIT Access':
      - 'Configuration options': configuration-options.md
  - GitHub: https://github.com/GoogleCloudPlatform/jit-groups